framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
            event.bus:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            external: '%env(MESSENGER_TRANSPORT_DSN)%'
            internal: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\StoreImage': internal
            'App\Message\ImageValidated': external
